# Generated by Django 4.2.20 on 2025-04-08 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
        migrations.AddField(
            model_name='project',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
